name: CI

on: [push, pull_request]

jobs:
  test:
    name: >-
      Test (${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - 3.0
          - 3.1
          - 3.2
          - jruby
    steps:
      - uses: actions/checkout@v2
      - uses: supercharge/redis-github-action@1.1.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
